### ISSUE TITLE
Objective-C alternative

### ISSUE THREAD

**Issue by syrakozz** [KevinJue/JS.OI-WKWebview#1]
Any Objective-C alternative, and pod version ?

**Comment by KevinJue** [comment]
@syrakozz 
Currently it's just a prototype, im working on when a got time so be patient.

But, why do you want an alternative in objective-c when you can use this feature, called mix and match, to write apps that have a mixed-language codebase, then you can use swift and objective-c in same project

**Comment by syrakozz** [comment]
+1

**Comment by KevinJue** [comment]
@syrakozz after your comment, i'm agree with you, a pod version is missing.
So i will include it as soon as possible #11.

Thanks to contribute.
Cheers.
